# Big Data Analytics Project - Spring 2026

## Notebook 1 - EDA and Initial Preprocessing 

This notebook covers **Exploratory Data Analysis (EDA) and Initial Preprocessing** for the three datasets used throughout this project:

- **NYC Yellow Taxi Trip Records** — trip-level data used for Structured Streaming (Notebook 5). We explore data quality issues (zero-distance/fare/passenger trips, short trips), perform RDD, DataFrame, and SparkSQL analyses, and clean the dataset for downstream use.
- **PaySim Financial Fraud Dataset** — synthetic mobile-money transaction log used for graph analytics (Notebook 4). We analyse class imbalance, account validity, balance consistency, and fraud patterns via SparkSQL.
- **Fashion-MNIST Image Dataset** — flat CSV image dataset used for ML pipelines and deep learning (Notebooks 2 & 3). We verify pixel ranges, class balance, and data integrity using all three Spark APIs.

All three datasets are cleaned and saved to `data/clean/` for use in subsequent notebooks.

### Group 16 Members:

- Ana Margarida Macedo (20250405) 
- Catarina Aboim (20250375)
- Margarida Craveiro (20250346)
- Matilde Simões (20250382)
- Lourenço Silva (20250453)

### <font color='#0000FF'>**Methodology**</font><a class="anchor" id="TOP"></a>

- [1. Chosen Datasets](#1)
    - [1.1 Yellow Taxis Dataset](#1.1)
    - [1.2 Financial Fraud Detection Dataset (PaySim subset)](#1.2)
    - [1.3 Fashion-MNIST Dataset](#1.3)
- [2. Metadata](#2)
    - [2.1 Yellow Taxis Dataset](#2.1)
    - [2.2 Financial Fraud Detection Dataset](#2.2)
    - [2.3 Fashion-MNIST Dataset](#2.3)
- [3. Setup](#3)
- [4. Library and Dataset Imports](#4)
    - [4.1 Yellow Taxis Dataset](#4.1)
    - [4.2 PaySim Dataset](#4.2)
    - [4.3 Fashion-MNIST Dataset](#4.3)
- [5. EDA - Yellow Taxis Dataset](#5)
    - [5.1 Preview](#5.1)
    - [5.2 Data Quality Analysis](#5.2)
        - [5.2.1 Zero-distance trips](#5.2.1)
        - [5.2.2 Zero-fare trips](#5.2.2)
        - [5.2.3 Zero-passenger trips](#5.2.3)
        - [5.2.4 Extremely short trips (< 60 seconds)](#5.2.4)
        - [5.2.5 Same origin/destination trips](#5.2.5)
        - [5.2.6 Extra and MTA tax = 0](#5.2.6)
    - [5.3 RDD EDA](#5.3)
    - [5.4 DF EDA - Null Analysis and Distributions](#5.4)
    - [5.5 SparkSQL - Temporal Analysis and YoY comparison](#5.5)
- [6. Initial Preprocessing - Yellow Taxis Dataset](#6)
- [7. EDA - PaySim Dataset](#7)
    - [7.1 Dataset Preview](#7.1)
    - [7.2 Class Imbalance](#7.2)
    - [7.3 Data Quality Analysis](#7.3)
        - [7.3.1 Unique values](#7.3.1)
        - [7.3.2 Account Validity](#7.3.2)
        - [7.3.3 Null values](#7.3.3)
        - [7.3.4 Transactions between the Same Account](#7.3.4)
        - [7.3.5 Zero-Amount Transactions](#7.3.5)
        - [7.3.6 Balance Consistency Analysis](#7.3.6)
        - [7.3.7 Transaction Amount Consistency Analysis](#7.3.7)
    - [7.4 Statistical Analysis of Target Variable](#7.4)
        - [7.4.1 Fraud Ratios - SparkSQL](#7.4.1)
        - [7.4.2 Total Fraudulent Amount per Type](#7.4.2)
        - [7.4.3 Fraud Rate per Type](#7.4.3)
        - [7.4.4 Identification of Potential "Money Mule" Accounts](#7.4.4)
        - [7.4.5 Cumulative Fraudulent Amount per Account](#7.4.5)
- [8. Initial Preprocessing - PaySim Dataset](#8)
- [9. EDA - Fashion-MNIST Dataset](#9)
    - [9.1 Preview](#9.1)
    - [9.2 Null Analysis - DataFrame API](#9.2)
    - [9.3 Pixel Value Range Check - RDD](#9.3)
    - [9.4 Type Consistency Check - SparkSQL](#9.4)
    - [9.5 Class Balance - SparkSQL](#9.5)
    - [9.6 Duplicates and Image-Format Consistency](#9.6)
- [10. Initial Preprocessing - Fashion-MNIST Dataset](#10)
- [11. Save Preprocessed Datasets](#11)


<a class="anchor" id="1">

# **1. Chosen Datasets**

[Back to TOP](#TOP)
</a>

<a class="anchor" id="1.1">

## **1.1 Yellow Taxis Dataset**

[Back to TOP](#TOP)
</a>

This dataset is published by the New York City Taxi & Limousine Commission (TLC) and is freely available under a U.S. Government Works license. It contains trip records from yellow medallion taxicabs, the iconic NYC street-hail taxis whose number is limited by a finite number of TLC-issued medallions.
Each record corresponds to a single trip and includes 19 columns capturing. For this project, we use 4 files spanning January 2015 and January, February, and March 2016. This selection enables a year-over-year comparison between January 2015 and January 2016, as well as a short intra-year trend analysis across Q1 2016.

**Role for the project:**
We chose this dataset because each row carries an explicit pickup timestamp, so we can replay the trip log as a continuous chronological event stream and simulate a real-time taxi-dispatch feed. This makes it a natural fit for demonstrating **Spark Structured Streaming** later in the project.

Important considerations:

- passenger_count is a driver-entered value and may be inaccurate
- trip_distance is reported by the taximeter and can be zero even when a fare was charged, suggesting meter or GPS errors
- Fare amounts can be negative due to billing adjustments

Link for the dataset: https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

<a class="anchor" id="1.2">

## **1.2 Financial Fraud Detection Dataset (PaySim subset)**

[Back to TOP](#TOP)
</a>

This dataset presents a synthetic representation of mobile money transactions, meticulously crafted to mirror the complexities of real-world financial activities while integrating fraudulent behaviors for research purposes. It aims to fill the gap in publicly available financial datasets for fraud detection studies and encompasses a variety of transaction types including CASH-IN, CASH-OUT, DEBIT, PAYMENT, and TRANSFER over a simulated period of 30 days, providing a comprehensive environment for evaluating fraud detection methodologies. It is scaled to 1/4 of the original dataset size for efficient use.

It utilizes aggregated data from actual financial logs of a mobile money service in an African country (like M-Pesa). In these systems, cash out transfers are made with use of an intermediary, the merchant. This intermediary receives the amount of the cash out transaction and provides the same amount in physical cash.

**Role for the project:** We chose this dataset because every transaction defines a directed edge from `nameOrig` to `nameDest`, turning the entire log into a large transaction graph using **GraphFrames**. It lets us run connected-components, PageRank-style influence analyses, and motif searches to surface money-mule rings and other coordinated fraud patterns that are invisible to row-level models.

Important considerations:

- **Transactions marked as fraudulent have been nullified,** emphasizing the importance of non-balance columns for fraud analysis.
- PaySim **does not simulate the balances for merchants,** which could present "incorrect" balances.
- When a transaction is flagged by the system, it means the transfer was stopped and did not go through.

Link for the dataset: https://www.kaggle.com/datasets/sriharshaeedala/financial-fraud-detection-dataset

<a class="anchor" id="1.3">

## **1.3 Fashion-MNIST Dataset**

[Back to TOP](#TOP)
</a>

Fashion-MNIST is an image classification dataset released by Zalando Research and made publicly available on Kaggle under the MIT license. It is intended as a direct drop-in replacement for the original MNIST handwritten-digit dataset, sharing the same image size (28x28 pixels), grayscale encoding, and train/test split sizes (60,000 training and 10,000 testing examples). Each image depicts a single clothing or accessory item photographed against a neutral background and is associated with one of 10 mutually exclusive class labels:

| Label | Class |
|:---:|:---|
| 0 | T-shirt/top |
| 1 | Trouser |
| 2 | Pullover |
| 3 | Dress |
| 4 | Coat |
| 5 | Sandal |
| 6 | Shirt |
| 7 | Sneaker |
| 8 | Bag |
| 9 | Ankle boot |

The dataset is provided in two formats on Kaggle: the original IDX binary files used by the MNIST community, and a flat CSV format where each row corresponds to a single image. In the CSV format, the first column contains the integer class label and the remaining 784 columns contain the pixel intensities (one per pixel of the 28x28 image), with values ranging from 0 (black) to 255 (white). The classes are perfectly balanced - exactly 7,000 images per class in the combined train + test split.

**Role for the project:** We chose Fashion-MNIST as the third dataset for this project because its image structure naturally supports both **classical ML (after flattening)** and **deep learning architectures** (CNNs over the 28x28 grid and RNNs/LSTMs over the 28 image rows as a sequence), allowing us to showcase the full **ML pipeline** functionality of PySpark together with distributed deep-learning workflows.

Important considerations:

- The dataset is clean by design (synthetic image processing, no missing pixels expected), but pixel range and type integrity must still be verified.
- Pixel values are integers in [0, 255]; any value outside this range or any non-integer entry would indicate corruption or a parsing error.
- Because Fashion-MNIST is small (~30 MB), the "big data" angle is justified through distributed data preparation and distributed model training rather than raw volume.

Link for the dataset: https://www.kaggle.com/datasets/zalando-research/fashionmnist


<a class="anchor" id="2">

# **2. Metadata**
</a>

---

<a class="anchor" id="2">

## **2.1 Yellow Taxis Dataset**
</a>

| Field | Description |
|---|---|
| **VendorID** | A code indicating the TPEP provider that provided the record: `1` = Creative Mobile Technologies, LLC · `2` = Curb Mobility|
| **tpep_pickup_datetime** | The date and time when the meter was engaged. |
| **tpep_dropoff_datetime** | The date and time when the meter was disengaged. |
| **passenger_count** | The number of passengers in the vehicle. |
| **trip_distance** | The elapsed trip distance in miles reported by the taximeter. |
| **RatecodeID** | The final rate code in effect at the end of the trip: `1` = Standard rate · `2` = JFK · `3` = Newark · `4` = Nassau or Westchester · `5` = Negotiated fare · `6` = Group ride · `99` = Null/unknown |
| **store_and_fwd_flag** | Whether the trip record was held in vehicle memory before sending to the vendor ("store and forward"): `Y` = store and forward trip · `N` = not a store and forward trip |
| **PULocationID** | TLC Taxi Zone in which the taximeter was engaged. |
| **DOLocationID** | TLC Taxi Zone in which the taximeter was disengaged. |
| **payment_type** | How the passenger paid for the trip: `0` = Flex Fare · `1` = Credit card · `2` = Cash · `3` = No charge · `4` = Dispute · `5` = Unknown · `6` = Voided trip |
| **fare_amount** | The time-and-distance fare calculated by the meter. |
| **extra** | Miscellaneous extras and surcharges. |
| **mta_tax** | Tax automatically triggered based on the metered rate in use. |
| **tip_amount** | Tip amount — automatically populated for credit card tips. Cash tips are not included. |
| **tolls_amount** | Total amount of all tolls paid in trip. |
| **improvement_surcharge** | Improvement surcharge assessed at flag drop (levied since 2015). |
| **total_amount** | Total amount charged to passengers. Does not include cash tips. |
| **congestion_surcharge** | Total amount collected in trip for NYS congestion surcharge. |
| **airport_fee** | Pick-up fee at LaGuardia and John F. Kennedy Airports only. |


> For more on fare fields, see: https://www.nyc.gov/site/tlc/passengers/taxi-fare.page

---

<a class="anchor" id="2">

## **2.2 Financial Fraud Detection Dataset**
</a>

| Field | Description |
|---|---|
| **step** | Unit of time where 1 step = 1 hour. Total simulation spans 744 steps (30 days). |
| **type** | Transaction type: `CASH-IN`, `CASH-OUT`, `DEBIT`, `PAYMENT`, or `TRANSFER`. |
| **amount** | Transaction amount in local currency. |
| **nameOrig** | Customer initiating the transaction. |
| **oldbalanceOrg** | Initiating customer's balance before the transaction. |
| **newbalanceOrig** | Initiating customer's balance after the transaction. |
| **nameDest** | Recipient customer of the transaction. |
| **oldbalanceDest** | Recipient's balance before the transaction. Not applicable for merchants (prefix `M`). |
| **newbalanceDest** | Recipient's balance after the transaction. Not applicable for merchants (prefix `M`). |
| **isFraud** | Flags transactions by fraudulent agents aiming to deplete accounts via transfers and cash-outs. |
| **isFlaggedFraud** | Flags illegal large-scale unauthorized transfers (any single transaction > 200,000). |


---

<a class="anchor" id="2">

## **2.3 Fashion-MNIST Dataset**

### **Class Labels**
</a>

| Label | Class |
|:---:|---|
| 0 | T-shirt/top |
| 1 | Trouser |
| 2 | Pullover |
| 3 | Dress |
| 4 | Coat |
| 5 | Sandal |
| 6 | Shirt |
| 7 | Sneaker |
| 8 | Bag |
| 9 | Ankle boot |

<a class="anchor" id="2">

### **Schema**
</a>

| Field | Description |
|---|---|
| **label** | Integer class identifier in range [0, 9] — see table above. |
| **pixel1 … pixel784** | 784 integer columns representing the flattened 28×28 grayscale image (row-major order). Values in [0, 255]: `0` = black, `255` = white. |

<a class="anchor" id="2">

### **Dataset Info**
</a>

| Property | Value |
|---|---|
| Training samples | 60,000 |
| Test samples | 10,000 |
| Class balance | Perfectly balanced — 6,000 train + 1,000 test per class |
| License | MIT |
| Source | [Kaggle — zalando-research/fashionmnist](https://www.kaggle.com/datasets/zalando-research/fashionmnist) |
| Paper | Xiao, Rasul & Vollgraf, *Fashion-MNIST: a Novel Image Dataset for Benchmarking Machine Learning Algorithms*, 2017 ([arXiv:1708.07747](https://arxiv.org/abs/1708.07747)) |

<a class="anchor" id="3">

# **3. Setup**

[Back to TOP](#TOP)
</a>


In [1]:
#!pip install pyspark
#!pip install pandas
#!pip install matplotlib
#!pip install kagglehub # to import Financial Fraud dataset

## Install Java 17
#!sudo apt-get update
#!sudo apt-get install -y openjdk-17-jdk-headless

In [2]:
# Confirm Java 17 install
!java -version

openjdk version "17.0.19" 2026-04-21
OpenJDK Runtime Environment (build 17.0.19+10-1-24.04.2-Ubuntu)
OpenJDK 64-Bit Server VM (build 17.0.19+10-1-24.04.2-Ubuntu, mixed mode, sharing)


<a class="anchor" id="4">

# **4. Library and Dataset Imports**

[Back to TOP](#TOP)
</a>


In [3]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
import kagglehub # to import Financial Fraud dataset
import pandas as pd
import matplotlib.pyplot as plt
import os, subprocess
from pyspark.sql.functions import col, desc

from pyspark.sql.functions import udf
from pyspark.sql.types import DoubleType

Local VSCode

In [4]:
# Find the real Java path from Homebrew
#result = subprocess.run(['brew', '--prefix', 'openjdk@17'], capture_output=True, text=True)
#java_home = result.stdout.strip()
#print(f"Homebrew Java prefix: {java_home}")

#os.environ['JAVA_HOME'] = java_home
#os.environ['PATH'] = java_home + '/bin:' + os.environ['PATH']

Lightning AI

In [5]:
# Set JAVA_HOME to Java 17 (for Lightning AI)
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]

For both:

In [6]:
# Start Spark session
spark = SparkSession.builder \
    .appName("BDA_Project") \
    .master("local[*]") \
    .config("spark.driver.memory", "6g") \
    .config("spark.executor.memory", "6g") \
    .config("spark.driver.maxResultSize", "2g") \
    .config("spark.sql.shuffle.partitions", "8") \
    .getOrCreate()

Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/06/02 23:51:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


<a class="anchor" id="4.1">

## **4.1 Yellow Taxis Dataset**

[Back to TOP](#TOP)
</a>


Context: In New York City, yellow taxis (medallion cabs) can pick up passengers anywhere, while green taxis (Boro Taxis) are restricted to hailing in outer boroughs and upper Manhattan. Both use meters and are regulated. Elsewhere, yellow often indicates high-visibility, traditional, or airport-focused services, while green may represent eco-friendly or specialized suburban vehicles

Data Download

In [7]:
# only runs this once
if not os.path.exists("data"):
    os.makedirs("data/raw", exist_ok=True)
    os.makedirs("data/clean", exist_ok=True)

    files = [
        "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-01.parquet",
        "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-01.parquet",
        "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-02.parquet",
        "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-03.parquet",
    ]

    for url in files:
        filename = url.split("/")[-1]
        output_path = f"data/raw/{filename}"

        print(f"Downloading {filename}...")
        subprocess.run(["curl", "-L", "-o", output_path, url], check=True)
        print(f"Saved to {output_path}\n")

else:
    print("'data' directory already exists. Skipping downloads.")

'data' directory already exists. Skipping downloads.


Having Jan 2015 + Jan/Feb/Mar 2016 lets us do year-over-year comparison (Jan 2015 vs Jan 2016) AND a short 3-month trend within 2016.

In [8]:
# Load data as DataFrames
df_taxi_012015 = (
    spark.read
    .parquet("data/raw/yellow_tripdata_2015-01.parquet")
)
df_taxi_012016 = (
    spark.read.parquet("data/raw/yellow_tripdata_2016-01.parquet")
)
df_taxi_022016 = (
    spark.read.parquet("data/raw/yellow_tripdata_2016-02.parquet")
)
df_taxi_032016 = (
    spark.read.parquet("data/raw/yellow_tripdata_2016-03.parquet")
)

In [9]:
# Load all taxi datasets as one
df_taxi_all = (
    spark.read
    .parquet("data/raw/yellow_tripdata_*.parquet")
)

26/06/02 23:51:39 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: data/raw/yellow_tripdata_*.parquet.
java.io.FileNotFoundException: File data/raw/yellow_tripdata_*.parquet does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:980)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:1301)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:970)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:462)
	at org.apache.spark.sql.execution.streaming.sinks.FileStreamSink$.hasMetadata(FileStreamSink.scala:58)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:384)
	at org.apache.spark.sql.catalyst.analysis.ResolveDataSource.org$apache$spark$sql$catalyst$analysis$ResolveDataSource$$loadV1BatchSource(ResolveDataSource.scala:143)
	at org.apache.spark

<a class="anchor" id="4.2">

## **4.2 PaySim Dataset**

[Back to TOP](#TOP)
</a>


In [10]:
# Download latest version
path = kagglehub.dataset_download("sriharshaeedala/financial-fraud-detection-dataset")

print("Path to dataset files:", path)
print(os.listdir(path))

Path to dataset files: /teamspace/studios/this_studio/.cache/kagglehub/datasets/sriharshaeedala/financial-fraud-detection-dataset/versions/1
['Synthetic_Financial_datasets_log.csv']


In [11]:
csv_file = os.path.join(path, "Synthetic_Financial_datasets_log.csv")

# Load as DataFrame
df_paysim = spark.read.csv(csv_file, header=True, inferSchema=True)

<a class="anchor" id="4.3">

## **4.3 Fashion-MNIST Dataset**

[Back to TOP](#TOP)
</a>

We download Fashion-MNIST from Kaggle using `kagglehub` and load the train/test CSV files as Spark DataFrames.

In [12]:
# Download latest version of Fashion-MNIST
fmnist_path = kagglehub.dataset_download("zalando-research/fashionmnist")

print("Path to dataset files:", fmnist_path)
print(os.listdir(fmnist_path))


Path to dataset files: /teamspace/studios/this_studio/.cache/kagglehub/datasets/zalando-research/fashionmnist/versions/4
['t10k-labels-idx1-ubyte', 'fashion-mnist_train.csv', 'train-labels-idx1-ubyte', 'train-images-idx3-ubyte', 'fashion-mnist_test.csv', 't10k-images-idx3-ubyte']


In [13]:
# Load the train and test CSVs as Spark DataFrames.
# header=True picks up the column names (label, pixel1, ..., pixel784).
# inferSchema=True lets Spark detect the integer dtypes from the data.
fmnist_train_csv = os.path.join(fmnist_path, "fashion-mnist_train.csv")
fmnist_test_csv  = os.path.join(fmnist_path, "fashion-mnist_test.csv")

df_fmnist_train = spark.read.csv(fmnist_train_csv, header=True, inferSchema=True)
df_fmnist_test  = spark.read.csv(fmnist_test_csv,  header=True, inferSchema=True)

<a class="anchor" id="5">

# **5. EDA - Yellow Taxis Dataset**

[Back to TOP](#TOP)
</a>

<a class="anchor" id="5.1">

## **5.1 Dataset Preview**

[Back to TOP](#TOP)
</a>


We will have our first look at the dataset.

In [14]:
# Cache dataset since we'll re-use them across the EDA below
df_taxi_all.cache()

DataFrame[VendorID: bigint, tpep_pickup_datetime: timestamp_ntz, tpep_dropoff_datetime: timestamp_ntz, passenger_count: bigint, trip_distance: double, RatecodeID: bigint, store_and_fwd_flag: string, PULocationID: bigint, DOLocationID: bigint, payment_type: bigint, fare_amount: double, extra: double, mta_tax: double, tip_amount: double, tolls_amount: double, improvement_surcharge: double, total_amount: double, congestion_surcharge: int, airport_fee: int]

In [15]:
print(
    f"df_taxi_012015 (Jan 2015): Rows: {df_taxi_012015.count():,}, Cols: {len(df_taxi_012015.columns)}\n"
    f"df_taxi_012016 (Jan 2016): Rows: {df_taxi_012016.count():,}, Cols: {len(df_taxi_012016.columns)}\n"
    f"df_taxi_022016 (Feb 2016): Rows: {df_taxi_022016.count():,}, Cols: {len(df_taxi_022016.columns)}\n"
    f"df_taxi_032016 (Mar 2016): Rows: {df_taxi_032016.count():,}, Cols: {len(df_taxi_032016.columns)}\n"
    f"df_taxi_all    (merged)  : Rows: {df_taxi_all.count():,}, Cols: {len(df_taxi_all.columns)}"
)

ERROR:root:KeyboardInterrupt while sending command.                 (0 + 4) / 5]
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt


KeyboardInterrupt: 

In [ ]:
df_taxi_all.show(20)
print(f"Dataset cached. \n Total rows: {df_taxi_all.count()}")
print(f"Total columns: {len(df_taxi_all.columns)}")

26/06/02 23:38:24 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|airport_fee|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+
|       1| 2015-01-01 00:11:33|  2015-01-01 00:16:48|              1|          1.0|         1|                 N|          41|         166|           1|        5.7|  0.5|    0.5|       1.

26/06/02 23:38:25 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


Dataset cached. 
 Total rows: 47225338
Total columns: 19


In [17]:
# For .parquet files, the schema is predefined: long, double
df_taxi_all.printSchema()

root
 |-- VendorID: long (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: long (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- PULocationID: long (nullable = true)
 |-- DOLocationID: long (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: integer (nullable = true)
 |-- airport_fee: integer (nullable = true)



In [ ]:
df_taxi_all.describe().show()

26/06/02 23:38:25 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.


26/06/02 23:38:27 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


+-------+------------------+------------------+-----------------+------------------+------------------+------------------+------------------+-------------------+------------------+-------------------+-------------------+------------------+-------------------+---------------------+------------------+--------------------+-----------+
|summary|          VendorID|   passenger_count|    trip_distance|        RatecodeID|store_and_fwd_flag|      PULocationID|      DOLocationID|       payment_type|       fare_amount|              extra|            mta_tax|        tip_amount|       tolls_amount|improvement_surcharge|      total_amount|congestion_surcharge|airport_fee|
+-------+------------------+------------------+-----------------+------------------+------------------+------------------+------------------+-------------------+------------------+-------------------+-------------------+------------------+-------------------+---------------------+------------------+--------------------+-----------

<a class="anchor" id="5.2">

## **5.2 Data Quality Analysis**

[Back to TOP](#TOP)
</a>

<a class="anchor" id="5.2.1">

### **5.2.1 Zero-distance trips**

[Back to TOP](#TOP)
</a>


The goal of this section is to identify record anomalies within the dataset—specifically "Zero-distance paid trips". These are transactions where the passenger was charged a fare (total_amount > 0), but the recorded GPS distance was zero (trip_distance == 0).

While Spark DataFrames are more modern and optimized, we are using RDDs (Resilient Distributed Datasets) here to perform low-level, row-based filtering. This allows us to understand how Spark distributes functional transformations across a cluster.

In [ ]:
anomalies_df = df_taxi_all.filter(
    (col("trip_distance") == 0) & (col("total_amount") > 0)
)

# Count total anomalies found
n_anomalies = anomalies_df.count()
print(f"Zero-distance paid trips: {n_anomalies}")

# Show first 5 examples
print("\nExamples of anomalies:")
anomalies_df.select("VendorID", "trip_distance", "total_amount").show(5)

26/06/02 23:40:09 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


Zero-distance paid trips: 259943

Examples of anomalies:
+--------+-------------+------------+
|VendorID|trip_distance|total_amount|
+--------+-------------+------------+
|       1|          0.0|         3.8|
|       1|          0.0|        15.3|
|       1|          0.0|         3.8|
|       2|          0.0|        15.8|
|       1|          0.0|         3.8|
+--------+-------------+------------+
only showing top 5 rows



26/06/02 23:40:12 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


The filtering process revealed 259943 records where the trip_distance is 0.0 but the total_amount is greater than 0.

These records represent approximately a significant portion of the dataset that could skew economic analysis (like average fare per mile).

Potential Causes: These anomalies typically correspond to:

1. Fixed Fees: Minimum fares or cancellation fees where the vehicle did not move.

2. Sensor Errors: GPS or odometer malfunctions during a trip.

3. Wait Time: Passengers being charged for waiting time while the taxi remained stationary.

<a class="anchor" id="5.2.2">

### **5.2.2 Zero-fare trips**

[Back to TOP](#TOP)
</a>


In [ ]:
zero_fare = df_taxi_all.filter(
    (F.col("fare_amount") == 0) & (F.col("trip_distance") > 0)
)
print(f"Zero-fare trips with actual distance: {zero_fare.count():,}")
zero_fare.select("VendorID", "trip_distance", "fare_amount", 
                  "total_amount", "payment_type").limit(10).show()

26/06/02 23:40:13 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


Zero-fare trips with actual distance: 7,913
+--------+-------------+-----------+------------+------------+
|VendorID|trip_distance|fare_amount|total_amount|payment_type|
+--------+-------------+-----------+------------+------------+
|       1|         10.2|        0.0|         0.3|           2|
|       1|          5.4|        0.0|       10.05|           4|
|       1|          0.5|        0.0|         0.3|           2|
|       1|          3.3|        0.0|         0.3|           2|
|       1|          0.1|        0.0|         0.3|           2|
|       1|          1.2|        0.0|         0.3|           2|
|       1|          1.5|        0.0|         0.3|           2|
|       1|         23.8|        0.0|       10.05|           3|
|       1|         21.3|        0.0|        5.63|           2|
|       1|          6.8|        0.0|         0.3|           2|
+--------+-------------+-----------+------------+------------+



26/06/02 23:40:14 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


7913 trips recorded actual distance but zero fare. These may represent 
complimentary rides, system errors, or driver overrides. Vendor 1 accounts for the vast majority, suggesting a vendor-specific recording issue.

<a class="anchor" id="5.2.3">

### **5.2.3 Zero-passenger trips**

[Back to TOP](#TOP)
</a>


In [ ]:
zero_pax = df_taxi_all.filter(F.col("passenger_count") == 0)
print(f"Zero-passenger trips: {zero_pax.count():,}")

# Breakdown by vendor — is one vendor worse at recording this?
zero_pax.groupBy("VendorID").count().show()

26/06/02 23:40:15 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


Zero-passenger trips: 8,187


26/06/02 23:40:16 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 365.4 MiB so far)


+--------+-----+
|VendorID|count|
+--------+-----+
|       2|  759|
|       1| 7428|
+--------+-----+



8187 trips recorded zero passengers, with Vendor 1 responsible for 90.7% of cases. Since passenger_count is a driver-entered value, this likely reflects driver negligence in updating the meter rather than actual empty vehicle trips.

<a class="anchor" id="5.2.4">

### **5.2.4 Extremely short trips (< 60 seconds)**

[Back to TOP](#TOP)
</a>


In [ ]:
df_taxi_all.withColumn(
    "duration_seconds",
    F.unix_timestamp("tpep_dropoff_datetime") - F.unix_timestamp("tpep_pickup_datetime")
).filter(
    (F.col("duration_seconds") < 60) & (F.col("duration_seconds") >= 0)
).select("duration_seconds", "trip_distance", "fare_amount", "total_amount") \
 .orderBy("duration_seconds") \
 .limit(10).show()

26/06/02 23:40:20 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


+----------------+-------------+-----------+------------+
|duration_seconds|trip_distance|fare_amount|total_amount|
+----------------+-------------+-----------+------------+
|               0|          0.0|        2.5|         3.8|
|               0|          7.0|       22.0|        25.3|
|               0|          0.0|        4.5|         5.8|
|               0|          0.0|       34.0|        35.3|
|               0|          0.0|       56.5|        57.8|
|               0|          0.0|        2.5|         3.8|
|               0|          0.0|       11.5|        12.8|
|               0|          0.0|        4.5|         5.8|
|               0|         1.76|        8.0|         8.8|
|               0|          0.0|        2.5|         3.8|
+----------------+-------------+-----------+------------+



All trips under 60 seconds recorded zero duration, suggesting timestamp 
precision is limited to the minute level in this dataset. Many also show zero distance, confirming these are likely meter errors or immediate cancellations rather than valid trips.

<a class="anchor" id="5.2.5">

### **5.2.5 Same origin/destination trips**

[Back to TOP](#TOP)
</a>


> **Note:** The TLC Parquet files used in this project do not contain GPS coordinate 
> columns (`pickup_longitude`, `pickup_latitude`, etc.), as these were removed from the 
> official dataset after 2016 for privacy reasons. As a proxy, we identify trips where 
> `trip_distance = 0` but a fare was still charged and passengers were recorded.

In [ ]:
# Note: This version of the TLC Parquet dataset does not include GPS coordinate columns
# (pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude).
# These were removed from the official TLC data after 2016 for privacy reasons.
# Same origin/destination analysis based on coordinates is therefore not applicable here.

# As an alternative, we identify trips with zero distance AND non-zero fare as a proxy
same_origin_proxy = df_taxi_all.filter(
    (F.col("trip_distance") == 0) &
    (F.col("total_amount") > 0) &
    (F.col("passenger_count") > 0)
)

print(f"Trips with zero distance but valid fare and passengers: {same_origin_proxy.count():,}")
same_origin_proxy.select("VendorID", "passenger_count", 
                          "trip_distance", "fare_amount", 
                          "total_amount", "payment_type").limit(10).show()

26/06/02 23:40:22 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


Trips with zero distance but valid fare and passengers: 258,592
+--------+---------------+-------------+-----------+------------+------------+
|VendorID|passenger_count|trip_distance|fare_amount|total_amount|payment_type|
+--------+---------------+-------------+-----------+------------+------------+
|       1|              1|          0.0|        2.5|         3.8|           2|
|       1|              2|          0.0|       14.0|        15.3|           2|
|       1|              1|          0.0|        2.5|         3.8|           3|
|       2|              1|          0.0|        2.5|        15.8|           1|
|       1|              1|          0.0|        2.5|         3.8|           2|
|       1|              1|          0.0|        4.5|         5.8|           2|
|       1|              2|          0.0|        2.5|         3.8|           3|
|       2|              1|          0.0|        4.5|         5.8|           2|
|       1|              1|          0.0|        2.5|         3.8|  

26/06/02 23:40:23 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


258592 trips show zero distance despite having valid passengers and fares. 
As GPS coordinates are unavailable in this dataset version (removed by TLC post-2016 for privacy), this serves as a proxy for same origin/destination trips. The overlap with zero-distance trips confirms these are the same anomaly population identified earlier.

<a class="anchor" id="5.2.6">

### **5.2.6 Extra and MTA tax = 0**

[Back to TOP](#TOP)
</a>


In [ ]:
zero_extras = df_taxi_all.filter(
    (F.col("extra") == 0) & (F.col("mta_tax") == 0)
)
print(f"Trips with extra=0 AND mta_tax=0: {zero_extras.count():,}")

# What percentage of total?
total = df_taxi_all.count()
pct = zero_extras.count() / total * 100
print(f"Percentage of total: {pct:.2f}%")

# Are these mostly off-peak hours? (extra is typically $0.50 rush hour / $1 overnight)
zero_extras.withColumn("hour", F.hour("tpep_pickup_datetime")) \
           .groupBy("hour").count() \
           .orderBy("hour").show()

26/06/02 23:40:24 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


Trips with extra=0 AND mta_tax=0: 158,665


26/06/02 23:40:26 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)
26/06/02 23:40:27 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


Percentage of total: 0.34%


26/06/02 23:40:28 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 365.4 MiB so far)


+----+-----+
|hour|count|
+----+-----+
|   0| 6651|
|   1| 5894|
|   2| 5057|
|   3| 4500|
|   4| 3944|
|   5| 2612|
|   6| 7245|
|   7| 6255|
|   8| 6362|
|   9| 6410|
|  10| 6773|
|  11| 7558|
|  12| 7829|
|  13| 9038|
|  14|11853|
|  15|11682|
|  16| 5907|
|  17| 5540|
|  18| 5548|
|  19| 5300|
+----+-----+
only showing top 20 rows



Only 0.34% of trips have both extra=0 and mta_tax=0. Contrary to 
expectations, these are not concentrated in off-peak hours. They appear 
throughout the day, suggesting these are edge cases rather than systematic off-peak patterns. This may indicate occasional meter configuration errors.

<a class="anchor" id="5.3">

## **5.3 RDD EDA**

[Back to TOP](#TOP)
</a>

This section calculates the **average fare per mile** for each taxi vendor. By aggregating the total revenue and total distance traveled per vendor, we can compare their pricing efficiency.

#### Methodology
To ensure accurate results, we follow these steps using the RDD API:
1. **Cleaning**: We filter out records with `trip_distance <= 0` or `total_amount <= 0` based on our previous anomaly analysis.
2. **Mapping**: We create key-value pairs where the key is the `VendorID` and the value is a tuple `(total_amount, trip_distance)`.
3. **Reduction**: Using `reduceByKey`, we sum the fares and distances for each vendor across the entire distributed dataset.
4. **Computation**: A final map transformation calculates the ratio: `Sum of Fares / Sum of Distances`.


In [ ]:
#Filter valid data and create (VendorID, (price, distance)) pairs
taxi_totals_rdd = df_taxi_all.rdd \
    .filter(lambda row: row.trip_distance > 0 and row.total_amount > 0) \
    .map(lambda row: (row.VendorID, (row.total_amount, row.trip_distance)))

# Sum the values by VendorID
# 'a' and 'b' represent tuples of (price, distance) from two different rows
vendor_sum_rdd = taxi_totals_rdd.reduceByKey(lambda a, b: (a[0] + b[0], a[1] + b[1]))

# Calculate the final average (Total Price / Total Distance)
# For each vendor, x[0] is the VendorID, x[1][0] is the sum of money, and x[1][1] is the sum of distance.
fare_per_mile_rdd = vendor_sum_rdd.map(lambda x: (x[0], x[1][0] / x[1][1]))

print("Results: Average Fare per Mile by Vendor")
results = fare_per_mile_rdd.collect()
for vendor, avg_fare in results:
    print(f"Vendor ID: {vendor} | Average Fare per Mile: ${avg_fare:.2f}")

Results: Average Fare per Mile by Vendor


26/06/02 23:40:30 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


Vendor ID: 1 | Average Fare per Mile: $1.30
Vendor ID: 2 | Average Fare per Mile: $5.35


The RDD aggregation revealed a significant disparity between the two vendors:
* **Vendor 1:** Approximately $1.30 per mile.
* **Vendor 2:** Approximately $5.35 per mile.

Vendor 2 is significantly more expensive per mile (over 4x higher than Vendor 1). This suggests that Vendor 2 likely operates in dense urban areas (like Manhattan) where short trips incur high base fares and slow-moving traffic increases the cost relative to the distance. In contrast, Vendor 1's lower rate suggests longer-distance trips, possibly airport transfers or highway routes, where the cost per mile is naturally diluted.

<a class="anchor" id="5.4">

## **5.4 DF EDA - Null Analysis and Distributions**

[Back to TOP](#TOP)
</a>


In [ ]:
# Null analysis

null_counts = df_taxi_all.select([
    F.sum(F.col(c).isNull().cast("int")).alias(c) 
    for c in df_taxi_all.columns
])

null_counts.toPandas().T.rename(columns={0: "null_count"}) \
           .sort_values("null_count", ascending=False)

26/06/02 23:45:19 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


,null_count
airport_fee,47225338
congestion_surcharge,47225338
improvement_surcharge,3
tpep_dropoff_datetime,0
tpep_pickup_datetime,0
VendorID,0
passenger_count,0
PULocationID,0
trip_distance,0
RatecodeID,0


Only airport_fee and congestion_surcharge are fully null, which is expected, as these surcharges did not exist in 2015/2016. Only 3 records have null improvement_surcharge, negligible and safely ignored.
All operational columns are null-free, confirming high data quality.

In [ ]:
# Payment type breakdown
df_taxi_all.groupBy("payment_type") \
           .count() \
           .withColumn("pct", F.round(F.col("count") / df_taxi_all.count() * 100, 2)) \
           .orderBy("count", ascending=False) \
           .toPandas()

# Vendor breakdown
df_taxi_all.groupBy("VendorID").count().toPandas()

26/06/02 23:45:32 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)
26/06/02 23:45:33 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 365.4 MiB so far)
26/06/02 23:45:35 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


,VendorID,count
0,2,25010782
1,1,22214556


Vendor 2 accounts for 52.9% of all trips vs Vendor 1 at 47.1%, suggesting a slight market dominance in the period analysed.

<a class="anchor" id="5.5">

## **5.5 SparkSQL - Temporal Analysis and YoY comparison**

[Back to TOP](#TOP)
</a>

SparkSQL is particularly well-suited for temporal analysis on the taxi dataset because time-based aggregations naturally take the form of relational queries. These operations involve multiple levels of aggregation, conditional filtering, and cross-period comparisons (e.g. January 2015 vs January 2016) that would require deeply chained .groupBy(), .agg(), and .join() calls in the DataFrame API. In SQL, the same logic is expressed declaratively and remains readable at a glance. SparkSQL also integrates seamlessly with Spark's Catalyst optimizer, meaning there is no performance trade-off.


In [ ]:
# Register the combined taxi DataFrame as a temp view for SQL queries
df_taxi_all.createOrReplaceTempView("taxi")

# --- YoY comparison: January 2015 vs January 2016 ---
spark.sql("""
    SELECT
        YEAR(tpep_pickup_datetime)                               AS year,
        COUNT(*)                                                 AS total_trips,
        ROUND(AVG(trip_distance), 2)                             AS avg_distance_miles,
        ROUND(AVG(fare_amount), 2)                               AS avg_fare_usd,
        ROUND(AVG(tip_amount / NULLIF(fare_amount, 0)) * 100, 2) AS avg_tip_pct,
        ROUND(SUM(total_amount), 2)                              AS total_revenue_usd
    FROM taxi
    WHERE MONTH(tpep_pickup_datetime) = 1
      AND YEAR(tpep_pickup_datetime) IN (2015, 2016)
      AND fare_amount > 0
      AND trip_distance > 0
    GROUP BY YEAR(tpep_pickup_datetime)
    ORDER BY year
""").show()

# --- Monthly trend within 2016 (Jan, Feb, Mar) ---
spark.sql("""
    SELECT
        MONTH(tpep_pickup_datetime)     AS month,
        COUNT(*)                        AS total_trips,
        ROUND(AVG(fare_amount), 2)      AS avg_fare_usd,
        ROUND(AVG(trip_distance), 2)    AS avg_distance_miles
    FROM taxi
    WHERE YEAR(tpep_pickup_datetime) = 2016
      AND fare_amount > 0
      AND trip_distance > 0
    GROUP BY MONTH(tpep_pickup_datetime)
    ORDER BY month
""").show()

# --- Top 5 hours with highest average fare ---
spark.sql("""
    SELECT
        HOUR(tpep_pickup_datetime)      AS hour_of_day,
        COUNT(*)                        AS trips,
        ROUND(AVG(fare_amount), 2)      AS avg_fare_usd,
        ROUND(AVG(trip_distance), 2)    AS avg_distance_miles
    FROM taxi
    WHERE fare_amount > 0
      AND trip_distance > 0
    GROUP BY HOUR(tpep_pickup_datetime)
    ORDER BY avg_fare_usd DESC
    LIMIT 5
""").show()

26/06/02 23:45:37 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 365.4 MiB so far)


+----+-----------+------------------+------------+-----------+-----------------+
|year|total_trips|avg_distance_miles|avg_fare_usd|avg_tip_pct|total_revenue_usd|
+----+-----------+------------------+------------+-----------+-----------------+
|2015|   12662663|             13.21|       11.87|      14.84|   1.9081928368E8|
|2016|   10836965|              4.52|       12.45|      14.96|   1.6899713791E8|
+----+-----------+------------------+------------+-----------+-----------------+



26/06/02 23:45:42 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 365.4 MiB so far)


+-----+-----------+------------+------------------+
|month|total_trips|avg_fare_usd|avg_distance_miles|
+-----+-----------+------------+------------------+
|    1|   10836965|       12.45|              4.52|
|    2|   11307330|       12.38|              3.45|
|    3|   12132058|       12.73|              6.03|
+-----+-----------+------------+------------------+



26/06/02 23:45:46 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 365.4 MiB so far)


+-----------+-------+------------+------------------+
|hour_of_day|  trips|avg_fare_usd|avg_distance_miles|
+-----------+-------+------------+------------------+
|          5| 469722|       15.85|              5.31|
|          4| 505676|       14.87|               4.2|
|         23|2165802|       13.13|              6.87|
|          3| 680573|       13.09|              3.51|
|          0|1678338|       13.03|              3.37|
+-----------+-------+------------+------------------+



<a class="anchor" id="2">

## **5.6. Visualization**
</a>

In [32]:
#!pip install "pyspark>=4.0" plotly "pandas>=2.2.0" "nbformat>=4.2.0"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.4/455.4 MB 101.0 MB/s  0:00:0400:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for pyspark: filename=pyspark-4.1.2-py2.py3-none-any.whl size=456079515 sha256=8cf165e9ca60d236dfc0eb7b4755203478763dcaef47441a1d43bfaed20ac344
  Stored in directory: /home/zeus/.cache/pip/wheels/e6/9c/35/b08622081a09dc48b9467b570ae170519430915aa3c8d27cf9
Successfully built pyspark
  Attempting uninstall: pyspark
    Found existing installation: pyspark 3.5.0
    Uninstalling pyspark-3.5.0:
      Successfully uninstalled pyspark-3.5.0


In [16]:
# a simple scatter plot to visualize the relationship between PULocationID and total_amount
# We pass the exact column name as strings to the x and y parameter
df_taxi_all.plot.scatter(x="PULocationID", y="total_amount")

26/06/02 23:52:28 WARN MemoryStore: Not enough space to cache rdd_72_2 in memory! (computed 832.9 MiB so far)
26/06/02 23:52:28 WARN BlockManager: Persisting block rdd_72_2 to disk instead.
26/06/02 23:52:28 WARN MemoryStore: Not enough space to cache rdd_72_1 in memory! (computed 831.6 MiB so far)
26/06/02 23:52:28 WARN BlockManager: Persisting block rdd_72_1 to disk instead.
26/06/02 23:52:28 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 829.5 MiB so far)
26/06/02 23:52:28 WARN BlockManager: Persisting block rdd_72_0 to disk instead.
26/06/02 23:52:28 WARN MemoryStore: Not enough space to cache rdd_72_3 in memory! (computed 844.8 MiB so far)
26/06/02 23:52:28 WARN BlockManager: Persisting block rdd_72_3 to disk instead.
26/06/02 23:52:43 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)
26/06/02 23:52:44 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)
26/06/02 23:52:46 WA

In [18]:
df_taxi_all.plot.scatter(x="total_amount", y="trip_distance")

26/06/02 23:57:36 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


In [22]:
df_taxi_all.select(
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "airport_fee"
).plot.box()

26/06/03 00:06:54 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)
26/06/03 00:07:43 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


In [17]:
fig = df_taxi_all.plot.scatter(
    x="total_amount",
    y="trip_distance",
    size="passenger_count",
    hover_name="payment_type",
    color="payment_type",
    color_continuous_scale="Plasma",
)

fig.show()

26/06/02 23:56:32 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


let's observe if longer trips always mean higher fares

In [19]:
fig = df_taxi_all.plot.scatter(
    x="fare_amount",
    y="trip_distance",
    size="passenger_count",
    hover_name="RatecodeID",
    color="RatecodeID",
    color_continuous_scale="Viridis",
)

fig.show()

26/06/02 23:59:36 WARN MemoryStore: Not enough space to cache rdd_72_0 in memory! (computed 549.9 MiB so far)


<a class="anchor" id="6">

# **6. Initial Preprocessing - Yellow Taxis Dataset**

[Back to TOP](#TOP)
</a>


In [ ]:
from pyspark.sql.types import IntegerType, DoubleType

# Cast columns to correct types for consistency and downstream compatibility
df_taxi_clean = df_taxi_all \
    .withColumn("VendorID",        F.col("VendorID").cast(IntegerType())) \
    .withColumn("passenger_count", F.col("passenger_count").cast(IntegerType())) \
    .withColumn("trip_distance",   F.col("trip_distance").cast(DoubleType())) \
    .withColumn("fare_amount",     F.col("fare_amount").cast(DoubleType())) \
    .withColumn("tip_amount",      F.col("tip_amount").cast(DoubleType())) \
    .withColumn("total_amount",    F.col("total_amount").cast(DoubleType()))

# Remove records with invalid or physically impossible values
df_taxi_clean = df_taxi_clean.filter(
    (F.col("trip_distance")   >  0) &
    (F.col("fare_amount")     >  0) &
    (F.col("total_amount")    >  0) &
    (F.col("passenger_count") >  0) &
    (F.col("passenger_count") <  5) &
    (F.col("tpep_pickup_datetime").isNotNull()) &
    (F.col("tpep_dropoff_datetime").isNotNull())
)

# Add derived columns useful for time-based and economic analysis
df_taxi_clean = df_taxi_clean \
    .withColumn("trip_duration_min",
        F.round((F.unix_timestamp("tpep_dropoff_datetime") - 
                 F.unix_timestamp("tpep_pickup_datetime")) / 60, 2)) \
    .withColumn("fare_per_mile",
        F.round(F.col("fare_amount") / F.col("trip_distance"), 2)) \
    .withColumn("pickup_hour",  F.hour("tpep_pickup_datetime")) \
    .withColumn("pickup_month", F.month("tpep_pickup_datetime")) \
    .withColumn("pickup_year",  F.year("tpep_pickup_datetime"))

# Remove trips with impossible durations
df_taxi_clean = df_taxi_clean.filter(
    (F.col("trip_duration_min") > 0) & # Exclude negative durations
    (F.col("trip_duration_min") < 180) # Exclude trips longer than 3 hours (extreme outliers)
)

# Summary: compare record counts before and after cleaning
print(f"Records before cleaning: {df_taxi_all.count():,}")
print(f"Records after cleaning:  {df_taxi_clean.count():,}")
df_taxi_clean.limit(5).show()

Records before cleaning: 47,225,338


Records after cleaning:  46,867,729


+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+-----------------+-------------+-----------+------------+-----------+
|VendorID|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|RatecodeID|store_and_fwd_flag|PULocationID|DOLocationID|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|airport_fee|trip_duration_min|fare_per_mile|pickup_hour|pickup_month|pickup_year|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+-----------------+-------------+-----------+------

The preprocessing pipeline removed 357,609 records (~0.76% of the total dataset), retaining 46,867,729 valid trips for analysis.

The low removal rate suggests the TLC dataset is overall high quality. The removed records correspond to the anomalies identified in the Data Quality.
Analysis: zero-distance trips, invalid fares, ghost trips with no passengers, and trips with impossible durations.

The 5 derived columns added (`trip_duration_min`, `fare_per_mile`, `pickup_hour`, `pickup_month`, `pickup_year`) will enable richer time-based and economic analysis in subsequent sections without requiring repeated computation.

Null values were not removed as a blanket rule. The null analysis in section 4.4 confirmed that core operational columns (fare_amount, trip_distance, passenger_count, pickup/dropoff timestamps) contain no null values.

The NULL values visible in `congestion_surcharge` and `airport_fee` are expected and intentional. These surcharges were not yet in effect in 2015/2016 and were only introduced by the TLC in later years. Dropping these rows would incorrectly eliminate the entire dataset.

In [ ]:
# Free the cached memory
df_taxi_all.unpersist()

<a class="anchor" id="7">

# **7. EDA - PaySim Dataset**

[Back to TOP](#TOP)
</a>


<a class="anchor" id="7.1">

## **7.1 Dataset Preview**

[Back to TOP](#TOP)
</a>

We will have our first look at the dataset.

In [ ]:
# Cache dataset since we'll re-use them across the EDA below
df_paysim.cache() 

# Show first 20 records and summary of the dataset
df_paysim.show(20)
print(f"Dataset cached. \nTotal records: {df_paysim.count()}")
print(f"Total columns: {len(df_paysim.columns)}")

+----+--------+---------+-----------+-------------+--------------+-----------+--------------+--------------+-------+--------------+
|step|    type|   amount|   nameOrig|oldbalanceOrg|newbalanceOrig|   nameDest|oldbalanceDest|newbalanceDest|isFraud|isFlaggedFraud|
+----+--------+---------+-----------+-------------+--------------+-----------+--------------+--------------+-------+--------------+
|   1| PAYMENT|  9839.64|C1231006815|     170136.0|     160296.36|M1979787155|           0.0|           0.0|      0|             0|
|   1| PAYMENT|  1864.28|C1666544295|      21249.0|      19384.72|M2044282225|           0.0|           0.0|      0|             0|
|   1|TRANSFER|    181.0|C1305486145|        181.0|           0.0| C553264065|           0.0|           0.0|      1|             0|
|   1|CASH_OUT|    181.0| C840083671|        181.0|           0.0|  C38997010|       21182.0|           0.0|      1|             0|
|   1| PAYMENT| 11668.14|C2048537720|      41554.0|      29885.86|M123070170

Dataset cached. 
Total records: 6362620
Total columns: 11


In [ ]:
df_paysim.printSchema()

root
 |-- step: integer (nullable = true)
 |-- type: string (nullable = true)
 |-- amount: double (nullable = true)
 |-- nameOrig: string (nullable = true)
 |-- oldbalanceOrg: double (nullable = true)
 |-- newbalanceOrig: double (nullable = true)
 |-- nameDest: string (nullable = true)
 |-- oldbalanceDest: double (nullable = true)
 |-- newbalanceDest: double (nullable = true)
 |-- isFraud: integer (nullable = true)
 |-- isFlaggedFraud: integer (nullable = true)



In [ ]:
df_paysim.describe().show()

26/05/10 20:33:18 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.


+-------+------------------+--------+------------------+-----------+------------------+-----------------+-----------+------------------+------------------+--------------------+--------------------+
|summary|              step|    type|            amount|   nameOrig|     oldbalanceOrg|   newbalanceOrig|   nameDest|    oldbalanceDest|    newbalanceDest|             isFraud|      isFlaggedFraud|
+-------+------------------+--------+------------------+-----------+------------------+-----------------+-----------+------------------+------------------+--------------------+--------------------+
|  count|           6362620| 6362620|           6362620|    6362620|           6362620|          6362620|    6362620|           6362620|           6362620|             6362620|             6362620|
|   mean|243.39724563151657|    NULL|179861.90354913048|       NULL| 833883.1040744851|855113.6685785787|       NULL|1100701.6665196505|1224996.3982019336|0.001290820448180152| 2.51468734577894E-6|
| stddev| 

From this initial analysis, the dataset seems fairly clean, having no evident errors or invalid values in the data. To confirm this, we will conduct a in-depth data quality analysis.

However, there are some type mismatches we will need to correct in the preprocessing phase:
    
- `isFraud` and `isFlaggedFraud` should be booleans
- for consistency, all numeric columns should have 2 decimal numbers

Moreover, null values will have to be analysed thoroughly since some key columns should not contain null values.

In [ ]:
total_count = df_paysim.count()

df_paysim.groupBy("type").count() \
    .withColumn("percentage", F.round((F.col("count") / total_count) * 100, 2)) \
    .orderBy(F.col("count").desc()) \
    .show()

+--------+-------+----------+
|    type|  count|percentage|
+--------+-------+----------+
|CASH_OUT|2237500|     35.17|
| PAYMENT|2151495|     33.81|
| CASH_IN|1399284|     21.99|
|TRANSFER| 532909|      8.38|
|   DEBIT|  41432|      0.65|
+--------+-------+----------+



Analysing the existing types of transactions and their representation in the dataset, we see that withdrawals (CASH_OUT) is the most common, closely followed by payments. Transfers between accounts and debits are underrepresented.

<a class="anchor" id="7.2">

## **7.2 Class Imbalance**

[Back to TOP](#TOP)
</a>

Using the Spark DataFrame API, we first inspect the distribution of transaction types.


In [ ]:
fraud_count = df_paysim.filter("isFraud = 1").count()
print(f"Total transactions: {total_count}")
print(f"Fraudulent transactions: {fraud_count}")
print(f"Percentage of fraudulent transactions: {(fraud_count/total_count)*100:.4f}%")

Total transactions: 6362620
Fraudulent transactions: 8213
Percentage of fraudulent transactions: 0.1291%


Initial exploration reveals a massive (6.3M transactions) but extremely imbalanced dataset, where fraudulent transactions represent only 0.1291% of the total volume.

<a class="anchor" id="7.3">

## **7.3 Data Quality Analysis**

[Back to TOP](#TOP)
</a>


In [ ]:
# Register it as a temporary view so SQL queries can reference it by name.
df_paysim.createOrReplaceTempView("paysim")

<a class="anchor" id="7.3.1">

### **7.3.1 Unique values**

[Back to TOP](#TOP)
</a>


In [ ]:
df_paysim.select("isFraud", "isFlaggedFraud").distinct().show()

+-------+--------------+
|isFraud|isFlaggedFraud|
+-------+--------------+
|      1|             0|
|      0|             0|
|      1|             1|
+-------+--------------+



We confirm that there are no other values other than 0 and 1, meaning it is safe to convert them to booleans. We will do this in the preprocessing phase.

Notably, the system never false-flagged a legitimate transaction. It misses some fraudulent transactions, but every flagged one is an actual fraud, meaning the **automated flag is conservative.**

In [ ]:
accountname_cols = ["nameOrig", "nameDest"]

for c in accountname_cols:
    unique_count = df_paysim.select(c).distinct().count()
    print(f"Unique {c}: {unique_count}")

Unique nameOrig: 6353307


Unique nameDest: 2722362


For every unique destination account there is about 3 unique origin accounts. This is likely because the merchants are often destination accounts for transactions such as CASH-IN and CASH-OUT, that together represent over 50% of the total transactions, as we saw before.

<a class="anchor" id="7.3.2">

### **7.3.2 Account Validity**

[Back to TOP](#TOP)
</a>

We will assess if all account numbers are valid based on their format. More specifically, we will look at the unique values for the first character of origin and destination accounts, as well as their string length.

In [ ]:
for c in accountname_cols:
    print(f"\n=== {c} ===")
    
    # Count per first character
    df_paysim.select(
        F.substring(F.col(c).cast("string"), 1, 1).alias("first_char")
    ).groupBy("first_char").count().orderBy("count", ascending=False).show()
    
    # Count per string length
    df_paysim.select(
        F.length(F.col(c).cast("string")).alias("str_length")
    ).groupBy("str_length").count().orderBy("str_length").show()


=== nameOrig ===


+----------+-------+
|first_char|  count|
+----------+-------+
|         C|6362620|
+----------+-------+



+----------+-------+
|str_length|  count|
+----------+-------+
|         5|     35|
|         6|    269|
|         7|   2718|
|         8|  26789|
|         9| 266807|
|        10|2667372|
|        11|3398630|
+----------+-------+


=== nameDest ===


+----------+-------+
|first_char|  count|
+----------+-------+
|         C|4211125|
|         M|2151495|
+----------+-------+

+----------+-------+
|str_length|  count|
+----------+-------+
|         2|      2|
|         4|     40|
|         5|     43|
|         6|    270|
|         7|   2736|
|         8|  26411|
|         9| 269498|
|        10|2666336|
|        11|3397284|
+----------+-------+



Transactions are only made from customers (C) and the destination account can be both a customer (C) or a merchant (M), confirming what we concluded before about the number of unique origin and destination accounts. Merchant-destined transactions represent a little under a third of total transactions. 

We also see that there is a big variation of string length for account numbers. Let's analyse the account names with under 5 characters to assess if they represent errors.

In [ ]:
df_paysim.filter(
    (F.length(F.col("nameOrig")) < 5) | (F.length(F.col("nameDest")) < 5)
).show(15)

+----+--------+---------+-----------+-------------+--------------+--------+--------------+--------------+-------+--------------+
|step|    type|   amount|   nameOrig|oldbalanceOrg|newbalanceOrig|nameDest|oldbalanceDest|newbalanceDest|isFraud|isFlaggedFraud|
+----+--------+---------+-----------+-------------+--------------+--------+--------------+--------------+-------+--------------+
|   9|CASH_OUT|236263.88| C778345121|        533.0|           0.0|    C970|         188.0|     306294.56|      0|             0|
|   9|CASH_OUT| 69842.68| C134431951|          0.0|           0.0|    C970|     236451.88|     306294.56|      0|             0|
|   9|CASH_OUT|187647.46|C1011818071|      45250.0|           0.0|    C970|     306294.56|     383704.66|      0|             0|
|   9|CASH_OUT|258253.78|C2009583763|          0.0|           0.0|    C970|     493942.02|     383704.66|      0|             0|
|   9| CASH_IN|219594.28|C1594517532|   3988358.63|    4207952.91|    C970|      752195.8|     38

There are no visible errors, let's narrow it down

In [ ]:
df_paysim.filter(
    (F.length(F.col("nameOrig")) < 4) | (F.length(F.col("nameDest")) < 4)
).show(15)

+----+--------+--------+-----------+-------------+--------------+--------+--------------+--------------+-------+--------------+
|step|    type|  amount|   nameOrig|oldbalanceOrg|newbalanceOrig|nameDest|oldbalanceDest|newbalanceDest|isFraud|isFlaggedFraud|
+----+--------+--------+-----------+-------------+--------------+--------+--------------+--------------+-------+--------------+
| 352| CASH_IN|33067.48| C373364764|1.846422699E7| 1.849729447E7|      C2|     218762.68|      185695.2|      0|             0|
| 546|CASH_OUT|23085.48|C1135709228|        658.0|           0.0|      C2|      185695.2|     208780.68|      0|             0|
+----+--------+--------+-----------+-------------+--------------+--------+--------------+--------------+-------+--------------+



Again, we see no visible errors and will assume that C2 is a valid account number, and that this account number does not have a fixed number of characters.

<a class="anchor" id="7.3.3">

### **7.3.3 Null values**

[Back to TOP](#TOP)
</a>


In [ ]:
df_paysim.select([
    F.sum(F.col(c).isNull().cast("int")).alias(c)
    for c in df_paysim.columns
]).show()

+----+----+------+--------+-------------+--------------+--------+--------------+--------------+-------+--------------+
|step|type|amount|nameOrig|oldbalanceOrg|newbalanceOrig|nameDest|oldbalanceDest|newbalanceDest|isFraud|isFlaggedFraud|
+----+----+------+--------+-------------+--------------+--------+--------------+--------------+-------+--------------+
|   0|   0|     0|       0|            0|             0|       0|             0|             0|      0|             0|
+----+----+------+--------+-------------+--------------+--------+--------------+--------------+-------+--------------+



There are no null values on the dataset.

<a class="anchor" id="7.3.4">

### **7.3.4 Transactions between the Same Account**

[Back to TOP](#TOP)
</a>

As another integrity check, we will see if there are transactions where the same account is both the origin and destination accounts

In [ ]:
df_paysim.filter("nameOrig = nameDest").count()

0

Transactions between the same account do not exist, showing no errors of this type.

<a class="anchor" id="7.3.5">

### **7.3.5 Zero-Amount Transactions**

[Back to TOP](#TOP)
</a>

Another possible error would be having transactions with `amount=0`.

In [ ]:
zero_transactions_count = df_paysim.filter(col("amount") == 0).count()
print(f"Number of transactions with zero amount: {zero_transactions_count}")

Number of transactions with zero amount: 16


In [ ]:
if zero_transactions_count == 0:
    print("No transactions with zero amount found.")
elif zero_transactions_count < 20:
    print(f"Transactions with zero amount (showing all {zero_transactions_count}):")
    df_paysim.filter(col("amount") == 0).show(zero_transactions_count, truncate=False)
else:
    print(f"Transactions with zero amount (showing first 20 of {zero_transactions_count}):")

Transactions with zero amount (showing all 16):
+----+--------+------+-----------+-------------+--------------+-----------+--------------+--------------+-------+--------------+
|step|type    |amount|nameOrig   |oldbalanceOrg|newbalanceOrig|nameDest   |oldbalanceDest|newbalanceDest|isFraud|isFlaggedFraud|
+----+--------+------+-----------+-------------+--------------+-----------+--------------+--------------+-------+--------------+
|212 |CASH_OUT|0.0   |C1510987794|0.0          |0.0           |C1696624817|0.0           |0.0           |1      |0             |
|250 |CASH_OUT|0.0   |C521393327 |0.0          |0.0           |C480398193 |0.0           |0.0           |1      |0             |
|279 |CASH_OUT|0.0   |C539112012 |0.0          |0.0           |C1106468520|538547.63     |538547.63     |1      |0             |
|387 |CASH_OUT|0.0   |C1294472700|0.0          |0.0           |C1325541393|7970766.57    |7970766.57    |1      |0             |
|425 |CASH_OUT|0.0   |C832555372 |0.0          |0

We conclude that there are **16 transactions with `amount == 0`** and all of them represent fraudulent transactions, which were not flagged, meaning they are not errors of the dataset.

<a class="anchor" id="7.3.6">

### **7.3.6 Balance Consistency Analysis**

[Back to TOP](#TOP)
</a>

A common indicator of fraud is a discrepancy between the transaction amount and the account's balance change. We implement a validation logic to flag transactions where the balance was not updated correctly.


In [ ]:
# Pure function to check integrity
def is_balance_consistent(row):
    #Check if (Initial Balance - Final Balance) is equal to the Amount (with an error margin of 0.01)
    diff = abs(abs((row.oldbalanceOrg - row.newbalanceOrig)) - row.amount)
    return diff < 0.01

# Apply the filter and count inconsistencies
inconsistent_frauds = df_paysim.filter("isFraud = 1").rdd.filter(lambda r: not is_balance_consistent(r))
inconsistent_non_frauds = df_paysim.filter("isFraud = 0").rdd.filter(lambda r: not is_balance_consistent(r))
consistent_frauds = df_paysim.filter("isFraud = 1").rdd.filter(lambda r: is_balance_consistent(r))
print(f"Fraudulent transactions with inconsistent balances: {inconsistent_frauds.count()}\nNon-fraudulent transactions with inconsistent balances: {inconsistent_non_frauds.count()}\nFraudulent transactions with consistent balances: {consistent_frauds.count()}")

Fraudulent transactions with inconsistent balances: 45
Non-fraudulent transactions with inconsistent balances: 3777773
Fraudulent transactions with consistent balances: 8168


The application of a Pure Function for validation uncovered 45 fraudulent transactions where a logical inconsistency exists between the transaction amount and the resulting account balance. However, we cannot conclude anything from this, given that there are 8168 fraudulent transactions with consistent balances and, more critically, more than **3.7 million legitimate transactions with insconsistent balances.**

Upon review of the dataset's details, we know that the balances for merchant accounts are not updated after each transaction, so we will analyse the ones that only include customer accounts.

In [ ]:
# Faster alternative: stay in RDD, avoid toDF()
base_rdd = df_paysim.filter("isFraud = 0").rdd.filter(lambda r: not is_balance_consistent(r)).cache()

merchant_either = base_rdd.filter(
    lambda r: r["nameOrig"].startswith("M") or r["nameDest"].startswith("M")
).count()
total = base_rdd.count()

print(f"Merchant-involved: {merchant_either:,} / {total:,} ({merchant_either/total*100:.1f}%)")

Merchant-involved: 1,155,712 / 3,777,773 (30.6%)


In [ ]:
# Investigate non-merchant inconsistent non-fraud transactions
non_merchant_rdd = base_rdd.filter(
    lambda r: not r["nameOrig"].startswith("M") and not r["nameDest"].startswith("M")
).cache()

non_merchant_df = non_merchant_rdd.toDF()

print(f"Non-merchant inconsistent non-fraud transactions: {non_merchant_df.count():,}")

# Breakdown by transaction type
print("=== Breakdown by Transaction Type ===")
# NOT big-data safe: orderBy used for readability only
non_merchant_df.groupBy("type").count() \
    .orderBy(F.desc("count")) \
    .show()

Non-merchant inconsistent non-fraud transactions: 2,622,061
=== Breakdown by Transaction Type ===


+--------+-------+
|    type|  count|
+--------+-------+
|CASH_OUT|1990315|
|TRANSFER| 508727|
| CASH_IN| 110676|
|   DEBIT|  12343|
+--------+-------+



Investigating deeper into one of the types, specifically the `TRANSFER` type:

In [ ]:
# Deep-dive into inconsistent TRANSFER transactions
transfer_inconsistent = non_merchant_df.filter(F.col("type") == "TRANSFER")

total_transfer = transfer_inconsistent.count()

# How many are zero-balance origin artifacts?
transfer_zero_orig = transfer_inconsistent.filter(
    (F.col("oldbalanceOrg") == 0)
).count()

# Account drained to zero: oldbalanceOrg > 0 but newbalanceOrig == 0
transfer_drained = transfer_inconsistent.filter(
    (F.col("oldbalanceOrg") > 0) & (F.col("newbalanceOrig") == 0)
).count()

# How many have zero destination balances (both sides flat)?
transfer_zero_dest = transfer_inconsistent.filter(
    (F.col("oldbalanceDest") == 0) & (F.col("newbalanceDest") == 0)
).count()

# How many have zero on BOTH sides?
transfer_zero_both = transfer_inconsistent.filter(
    (F.col("oldbalanceOrg") == 0) & (F.col("newbalanceOrig") == 0) &
    (F.col("oldbalanceDest") == 0) & (F.col("newbalanceDest") == 0)
).count()

truly_unexplained = total_transfer - transfer_zero_orig - transfer_drained

print(f"Inconsistent TRANSFER (non-merchant, non-fraud): {total_transfer:,}")
print(f"  → Zero old origin balance:            {transfer_zero_orig:,} ({transfer_zero_orig/total_transfer*100:.1f}%)")
print(f"  → Account drained to zero:     {transfer_drained:,} ({transfer_drained/total_transfer*100:.1f}%)")
print(f"  → Zero dest balance:                          {transfer_zero_dest:,} ({transfer_zero_dest/total_transfer*100:.1f}%)")
print(f"  → Truly unexplained:                          {truly_unexplained:,}")

# Sample a few truly unexplained ones to inspect manually
transfer_inconsistent.filter(
    ~((F.col("oldbalanceOrg") == 0) & (F.col("newbalanceOrig") == 0)) &  # exclude zero origin artifact
    ~(F.col("newbalanceOrig") == 0) &                                      # exclude drained to zero
    ~((F.col("oldbalanceDest") == 0) & (F.col("newbalanceDest") == 0))    # exclude zero dest artifact
).select("nameOrig", "nameDest", "amount", "oldbalanceOrg", "newbalanceOrig", "oldbalanceDest", "newbalanceDest") \
 .limit(10).show(truncate=False)

Inconsistent TRANSFER (non-merchant, non-fraud): 508,727
  → Zero old origin balance:            282,779 (55.6%)
  → Account drained to zero:     224,728 (44.2%)
  → Zero dest balance:                          92 (0.0%)
  → Truly unexplained:                          1,220
+-----------+-----------+----------+-------------+--------------+--------------+--------------+
|nameOrig   |nameDest   |amount    |oldbalanceOrg|newbalanceOrig|oldbalanceDest|newbalanceDest|
+-----------+-----------+----------+-------------+--------------+--------------+--------------+
|C2142129482|C1170794006|169106.97 |575667.54    |575667.54     |575667.54     |22190.99      |
|C33951224  |C1721246982|423234.24 |1183874.19   |760639.94     |2316019.71    |2575739.64    |
|C2125244718|C748241311 |248768.2  |310245.27    |61477.06      |3013106.83    |3447714.21    |
|C1796504623|C447691425 |202143.74 |434299.82    |232156.07     |4100039.01    |6795453.82    |
|C691851752 |C1092318644|858733.8  |1220989.75   |3622

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/pyspark/python/lib/pyspark.zip/pyspark/daemon.py", line 233, in manager
    code = worker(sock, authenticated)
  File "/opt/anaconda3/lib/python3.13/site-packages/pyspark/python/lib/pyspark.zip/pyspark/daemon.py", line 87, in worker
    outfile.flush()
    ~~~~~~~~~~~~~^^
BrokenPipeError: [Errno 32] Broken pipe


**Concluding:** This mismatch persists on all types of transactions except for `PAYMENT`. The deep analysis into the 508,727 `TRANSFER` inconsistent transactions shows that **most errors** happen when the **origin account's balance is zero before the transfer (55.6%)** or when the origin account has a balance>0 deposited but it **does not have enough funds to conclude the transfer (44.2%).**

For this reason, and given that the PaySim dataset is known to have balance inconsistencies, we will only consider balance values as correct for `PAYMENT` transactions.

<a class="anchor" id="7.3.7">

### **7.3.7 Transaction Amount Consistency Analysis**

[Back to TOP](#TOP)
</a>

Following the previous analysis, we will go further into transaction amount consistency with the origin account balance. For all transactions except for `CASH_IN` transactions, we will check for transactions where the `amount` is bigger than the `oldbalanceOrg`, which should not be possible. For the `CASH_IN` transactions, the same will be done, but for `newbalanceOrg`.


In [ ]:
print(f"Non CASH_IN Transactions with amount > oldbalanceOrg and isFraud = 0: {df_paysim.filter("amount > oldbalanceOrg AND isFraud = 0 AND type != 'CASH_IN'").count()}")

print(f"CASH_IN Transactions with amount > newbalanceOrig and isFraud = 0: {df_paysim.filter("type = 'CASH_IN' AND isFraud = 0 AND amount > newbalanceOrig").count()}")

Non CASH_IN Transactions with amount > oldbalanceOrg and isFraud = 0: 3601515
CASH_IN Transactions with amount > newbalanceOrig and isFraud = 0: 0


In [ ]:
df_paysim.filter("amount > oldbalanceOrg AND isFraud = 0 AND type != 'CASH_IN'") \
         .groupBy("type") \
         .count() \
         .orderBy("count", ascending=False) \
         .show()

+--------+-------+
|    type|  count|
+--------+-------+
|CASH_OUT|1981098|
| PAYMENT|1101124|
|TRANSFER| 507507|
|   DEBIT|  11786|
+--------+-------+



With this analysis, we conclude that the Paysim dataset's amount and balance relationships are not reliable, showing plenty of mismatches, except for `CASH_IN` transactions.

<a class="anchor" id="7.4">

## **7.4 Statistical Analysis of Target Variable**

[Back to TOP](#TOP)
</a>


<a class="anchor" id="7.4.1">

### **7.4.1 Fraud Ratios - SparkSQL**

[Back to TOP](#TOP)
</a>

Analysing the percentage of transactions that:

- Were flagged and actually were fraud
- Were not flagged but were fraud
- Were fraud and were flagged


In [ ]:
spark.sql("""
    SELECT 'Flagged and actually fraud (Precision)'   AS metric,
        ROUND(SUM(CASE WHEN isFlaggedFraud = 1 AND isFraud = 1 THEN 1 ELSE 0 END)
            / NULLIF(SUM(isFlaggedFraud), 0) * 100, 2) AS percentage
    FROM paysim

    UNION ALL

    SELECT 'Fraud but not flagged (Miss Rate)'        AS metric,
        ROUND(SUM(CASE WHEN isFlaggedFraud = 0 AND isFraud = 1 THEN 1 ELSE 0 END)
            / NULLIF(SUM(isFraud), 0) * 100, 2)        AS percentage
    FROM paysim

    UNION ALL

    SELECT 'Fraud that was flagged (Recall)'          AS metric,
        ROUND(SUM(CASE WHEN isFraud = 1 AND isFlaggedFraud = 1 THEN 1 ELSE 0 END)
            / NULLIF(SUM(isFraud), 0) * 100, 2)        AS percentage
    FROM paysim
""").show(truncate=False)

+--------------------------------------+----------+
|metric                                |percentage|
+--------------------------------------+----------+
|Flagged and actually fraud (Precision)|100.0     |
|Fraud but not flagged (Miss Rate)     |99.81     |
|Fraud that was flagged (Recall)       |0.19      |
+--------------------------------------+----------+



From this analysis, we confirm what we stated previously. The automated flag system is accurate, but very conservative. It missed 99.81% of the fraud transactions.

<a class="anchor" id="7.4.2">

### **7.4.2 Total Fraudulent Amount per Type**

[Back to TOP](#TOP)
</a>

RDD-based Aggregation: We aim to calculate the total monetary volume of fraud for each transaction type to determine where the highest financial risk lies.


In [ ]:
#Map: (type, amount) only for frauds
fraud_map = df_paysim.filter("isFraud = 1").rdd.map(lambda row: (row.type, row.amount))

#Reduce: Sum the values
fraud_totals = fraud_map.reduceByKey(lambda a, b: a + b)

print("Total Stolen Amount per Transaction Type:")
for tType, total in fraud_totals.collect():
    print(f"- {tType}: ${total:,.2f}")

Total Stolen Amount per Transaction Type:


- TRANSFER: $6,067,213,184.01
- CASH_OUT: $5,989,202,243.83


<a class="anchor" id="7.4.3">

### **7.4.3 Fraud Rate per Type**

[Back to TOP](#TOP)
</a>


In [ ]:
spark.sql("""
    SELECT
        type,
        COUNT(*) AS total_transactions,
        SUM(isFraud) AS fraud_count,
        ROUND(SUM(isFraud) / COUNT(*) * 100, 2) AS fraud_rate_pct
    FROM paysim
    GROUP BY type
    ORDER BY fraud_rate_pct DESC
""").show()

+--------+------------------+-----------+--------------+
|    type|total_transactions|fraud_count|fraud_rate_pct|
+--------+------------------+-----------+--------------+
|TRANSFER|            532909|       4097|          0.77|
|CASH_OUT|           2237500|       4116|          0.18|
| PAYMENT|           2151495|          0|           0.0|
|   DEBIT|             41432|          0|           0.0|
| CASH_IN|           1399284|          0|           0.0|
+--------+------------------+-----------+--------------+



By implementing the MapReduce pattern (map followed by reduceByKey), the analysis identified a staggering financial impact exceeding $12 billion in total losses.

The losses are almost equally split between TRANSFER ($6.06B) and CASH_OUT ($5.99B). This symmetry suggests a structured criminal "two-step" pattern: funds are first moved to a secondary account via a Transfer and immediately liquidated through a Cash Out to erase the digital trail.

<a class="anchor" id="7.4.4">

### **7.4.4 Identification of Potential "Money Mule" Accounts**

[Back to TOP](#TOP)
</a>

To further investigate the fraud network, we performed a grouping analysis on the destination accounts (`nameDest`). Unlike victim accounts, which are usually targeted once, destination accounts that appear multiple times in fraudulent transactions are highly likely to be controlled by the fraudulent agents.


In [ ]:
#See which accounts receive the most fraudulent money
df_paysim.filter("isFraud = 1") \
  .groupBy("nameDest") \
  .agg(F.count("isFraud").alias("fraud_count"), 
       F.sum("amount").alias("total_stolen")) \
  .orderBy(F.col("fraud_count").desc()) \
  .show(10)

+-----------+-----------+------------------+
|   nameDest|fraud_count|      total_stolen|
+-----------+-----------+------------------+
| C185805228|          2|        1124385.07|
|  C52390890|          2|        2662695.58|
| C803116137|          2|1744765.6900000002|
| C935310781|          2|         544064.51|
| C104038589|          2|        2202769.97|
|C1013511446|          2|2994972.1999999997|
|C1827219533|          2|         907503.17|
| C904300960|          2|        1427683.17|
| C200064275|          2|            8847.0|
| C410033330|          2|         133781.84|
+-----------+-----------+------------------+
only showing top 10 rows


**Findings:**
1. The top 10 destination accounts were each involved in at least 2 high-value fraudulent transactions. 
2. Certain accounts aggregated financial volumes exceeding **$7 million**, highlighting their role as primary nodes in the money laundering process.
3. This grouping technique using `groupBy` and `agg` (aggregated functions) demonstrates how Spark can be used to identify complex network patterns across millions of records that would be invisible in a row-by-row analysis.

In [ ]:
df_paysim.createOrReplaceTempView("fraud_data")

spark.sql("""
    WITH fraud_tiers AS (
        SELECT amount, type,
               CASE 
                   WHEN amount > 1000000 THEN 'High Impact'
                   WHEN amount > 100000 THEN 'Medium Impact'
                   ELSE 'Low Impact'
               END as impact_level
        FROM fraud_data
        WHERE isFraud = 1
    )
    SELECT impact_level, COUNT(*) as count, SUM(amount) as total
    FROM fraud_tiers
    GROUP BY impact_level
    ORDER BY total DESC
""").show()

+-------------+-----+-------------------+
| impact_level|count|              total|
+-------------+-----+-------------------+
|  High Impact| 2706|  1.046072230895E10|
|Medium Impact| 3800|     1.5226730668E9|
|   Low Impact| 1707|7.302005208999997E7|
+-------------+-----+-------------------+



By registering the dataset as a Temporary View and utilizing Spark SQL, it was possible to segment the fraudulent activities into tiered impact levels. This approach, leveraging Common Table Expressions (CTEs) and Conditional Logic (CASE statements), provides a clear business-centric view of financial risk, proving that the majority of stolen volume is concentrated in high-impact transactions exceeding $1,000,000.

<a class="anchor" id="7.4.5">

### **7.4.5 Cumulative Fraudulent Amount per Account**

[Back to TOP](#TOP)
</a>

It is often the case in real life fraud scenarios that the same bank account suffers multiple times over time. It is a common tactic for scammers to drain the same account progressively once they notice the scheme works.

Using Spark Window Functions, we will track the cumulative amount moved by each account over time (steps) to verify if this behaviour is present in our dataset.


In [ ]:
from pyspark.sql.window import Window

# Definir a janela: por conta de origem, ordenada pelo tempo (step)
windowSpec = Window.partitionBy("nameOrig").orderBy("step")

# Calcular o valor acumulado
df_accumulated = df_paysim.withColumn(
    "cumulative_amount",
    F.round(F.sum("amount").over(windowSpec), 2)
)

# Mostrar contas que movimentaram valores críticos acumulados
df_accumulated.filter("isFraud = 1").orderBy(F.desc("cumulative_amount")).select("nameOrig", "step", "amount", "cumulative_amount").show(10)

+-----------+----+------+-----------------+
|   nameOrig|step|amount|cumulative_amount|
+-----------+----+------+-----------------+
|C1131684691| 685| 1.0E7|            1.0E7|
|C1237313447|  82| 1.0E7|            1.0E7|
| C200219666| 674| 1.0E7|            1.0E7|
|C1251439451| 212| 1.0E7|            1.0E7|
| C292642955| 554| 1.0E7|            1.0E7|
|C1507276112| 440| 1.0E7|            1.0E7|
|C1790027985| 230| 1.0E7|            1.0E7|
|C1274910960| 160| 1.0E7|            1.0E7|
|C1930318116| 617| 1.0E7|            1.0E7|
|C1066838925| 303| 1.0E7|            1.0E7|
+-----------+----+------+-----------------+
only showing top 10 rows


It appears that for most accounts, this scenario does not happen since the amount and the cumulative_amount are exactly the same. Let's check if this is the case for all fraudulent accounts.

In [ ]:
fraud_accumulated = df_accumulated.filter("isFraud = 1")

mismatch_count = fraud_accumulated.filter(
    F.col("cumulative_amount") != F.col("amount")
).count()

mismatch_df = fraud_accumulated.filter(
    F.col("cumulative_amount") != F.col("amount")
).select("nameOrig", "step", "amount", "cumulative_amount")

match_count = fraud_accumulated.filter(
    F.col("cumulative_amount") == F.col("amount")
).count()

total_count = fraud_accumulated.count()

print(f"Total fraudulent rows:              {total_count}")
print(f"Rows where amount == cumulative:    {match_count}")
print(f"Rows where amount != cumulative:    {mismatch_count}")

if mismatch_count == 0:
    print("\nAll fraudulent rows have cumulative_amount == amount.")
    print("These accounts performed exactly one fraudulent transaction.")
else:
    print(f"\n{mismatch_count} rows show multi-step fraud accumulation.")
    if mismatch_count < 20:
        mismatch_df.show(mismatch_count)
    else:
        mismatch_df.show(20)

Total fraudulent rows:              8213
Rows where amount == cumulative:    8195
Rows where amount != cumulative:    18

18 rows show multi-step fraud accumulation.


+-----------+----+----------+-----------------+
|   nameOrig|step|    amount|cumulative_amount|
+-----------+----+----------+-----------------+
|C1851065642| 601|1054244.29|       1155380.27|
| C483009518| 297|3105902.49|       3106348.37|
|C1191696703| 408| 2567602.1|       3215956.12|
|C1882162040| 537| 127447.68|        261285.59|
|C2004363483| 461|1028284.82|       1300743.12|
| C812001868| 379| 4445514.2|       4704536.85|
| C850961884| 727| 263401.81|        306941.99|
|C1015856166| 453|2600970.32|       2603467.05|
|C1127304441| 475| 876753.11|       1049698.51|
|C1885333477| 477|  815297.9|        974415.93|
| C803411135| 185| 164213.17|         340470.2|
|C1044518032| 388|  20393.12|         98996.58|
|C1899367925| 323|  25761.04|         35435.68|
| C357911107| 596| 204721.27|        340746.04|
| C471097879| 559| 127564.33|        156935.41|
| C929585215| 342| 348952.97|        423231.76|
|C1498185758| 205| 566156.42|        634612.76|
| C876181265| 243|1290193.08|        129

From the output, we conclude that successive fraud on the same account happens very rarely, only on 18 accounts. Since the `amount` is equal to the `cumulative amount` in most rows (8195 out of 8213), we conclude that fraud happens mostly once per account, rather than multiple times, which is often the case in real fraud scenarios.

<a class="anchor" id="2">

## **7.5. Visualization**
</a>

In [24]:
# Box plots — PaySim
df_paysim.select("amount",
                "oldbalanceOrg",
                "newbalanceOrig",
                "oldbalanceDest",
                "newbalanceDest",
                "step").plot.box()

In [29]:
# Scatter plot — PaySim
df_paysim.plot.scatter(x="amount", y="newbalanceOrig")

In [27]:
# Scatter plot — PaySim
df_paysim.plot.scatter(x="amount", y="oldbalanceOrg")

In [25]:
# shows if the transaction amount relates to the sender's original balance
fig = df_paysim.plot.scatter(
    x="amount",
    y="oldbalanceOrg",
    size="newbalanceOrig",
    hover_name="type",
    color="type",
    color_continuous_scale="Viridis",
)
fig.show()

<a class="anchor" id="8">

# **8. Initial Preprocessing - PaySim Dataset**

[Back to TOP](#TOP)
</a>


Enforce:

- boolean types on `isFraud` and `FlaggedFraud` columns
- 2 decimal numbers on numeric columns

In [ ]:
numeric_cols = ["amount", "oldbalanceOrg", "newbalanceOrig", "oldbalanceDest", "newbalanceDest"]

df_paysim_clean = df_paysim \
    .withColumn("isFraud", F.col("isFraud").cast(BooleanType())) \
    .withColumn("isFlaggedFraud", F.col("isFlaggedFraud").cast(BooleanType()))

for c in numeric_cols:
    df_paysim_clean = df_paysim_clean.withColumn(c, F.round(F.col(c), 2))

In [ ]:
# Free the cached memory
df_paysim.unpersist()

<a class="anchor" id="9">

# **9. EDA - Fashion-MNIST Dataset**

[Back to TOP](#TOP)
</a>

In this section we perform a basic exploratory analysis of the Fashion-MNIST dataset to verify the integrity of the data before training. Because the dataset is fundamentally image data flattened into 785 tabular columns, the checks focus on schema correctness, value ranges (pixels should be integers in `[0, 255]` and labels in `[0, 9]`), null values, and class balance. We deliberately mix the **DataFrame API**, the **RDD API**, and **Spark SQL** across the subsections to demonstrate each style.


<a class="anchor" id="9.1">

## **9.1 Preview**

[Back to TOP](#TOP)
</a>

We start with a structural overview: row counts, schema, and a quick visual inspection of the first few label values and a handful of pixels (the full row is 785 columns wide, so we slice).


In [ ]:
# Cache datasets since we'll re-use them across the EDA below
df_fmnist_train.cache()
df_fmnist_test.cache()

In [ ]:
# Row counts already printed above; re-state for self-contained section
print(f"Train rows: {df_fmnist_train.count():,}")
print(f"Test  rows: {df_fmnist_test.count():,}")
print(f"Columns   : {len(df_fmnist_train.columns)} (1 label + 784 pixel features)")

# Preview - show label + first 6 pixels of the first 5 training rows
# (a full printSchema would dump 785 lines, so a comprehensive type check
#  is done later in section 9.4)
df_fmnist_train.select(["label"] + [f"pixel{i}" for i in range(1, 7)]).limit(5).show()


Train rows: 60,000
Test  rows: 10,000
Columns   : 785 (1 label + 784 pixel features)
root
 |-- label: integer (nullable = true)
 |-- pixel1: integer (nullable = true)
 |-- pixel2: integer (nullable = true)
 |-- pixel3: integer (nullable = true)
 |-- pixel4: integer (nullable = true)
 |-- pixel5: integer (nullable = true)

+-----+------+------+------+------+------+------+------+------+------+-------+-------+
|label|pixel1|pixel2|pixel3|pixel4|pixel5|pixel6|pixel7|pixel8|pixel9|pixel10|pixel11|
+-----+------+------+------+------+------+------+------+------+------+-------+-------+
|    2|     0|     0|     0|     0|     0|     0|     0|     0|     0|      0|      0|
|    9|     0|     0|     0|     0|     0|     0|     0|     0|     0|      0|      0|
|    6|     0|     0|     0|     0|     0|     0|     0|     5|     0|      0|      0|
|    0|     0|     0|     0|     1|     2|     0|     0|     0|     0|      0|    114|
|    3|     0|     0|     0|     0|     0|     0|     0|     0|    

<a class="anchor" id="9.2">

## **9.2 Null Analysis - DataFrame API**

[Back to TOP](#TOP)
</a>

Image-classification datasets typically have no nulls (every pixel position is filled with an intensity, even if 0), but we verify this assumption explicitly. We use the **DataFrame API** with a single `agg` call summing `isNull` indicators across all 785 columns - this is one Spark job that scans the data once.


In [ ]:
# Count nulls across all columns in one pass (DataFrame API)
null_counts_train = df_fmnist_train.agg(*[
    F.sum(F.col(c).isNull().cast("int")).alias(c) for c in df_fmnist_train.columns
]).collect()[0].asDict()

total_nulls_train = sum(null_counts_train.values())
print(f"Total nulls in train set: {total_nulls_train}")

null_counts_test = df_fmnist_test.agg(*[
    F.sum(F.col(c).isNull().cast("int")).alias(c) for c in df_fmnist_test.columns
]).collect()[0].asDict()

total_nulls_test = sum(null_counts_test.values())
print(f"Total nulls in test  set: {total_nulls_test}")

# If any column had nulls, list them
problematic = {k: v for k, v in null_counts_train.items() if v > 0}
if problematic:
    print("Columns with nulls (train):", problematic)
else:
    print("No null values detected in either split.")


26/05/14 18:06:37 WARN DAGScheduler: Broadcasting large task binary with size 1035.7 KiB
26/05/14 18:06:41 WARN DAGScheduler: Broadcasting large task binary with size 1633.5 KiB


Total nulls in train set: 0


26/05/14 18:06:45 WARN DAGScheduler: Broadcasting large task binary with size 1035.9 KiB
26/05/14 18:06:46 WARN DAGScheduler: Broadcasting large task binary with size 1635.0 KiB


Total nulls in test  set: 0
No null values detected in either split.


<a class="anchor" id="9.3">

## **9.3 Pixel Value Range Check - RDD**

[Back to TOP](#TOP)
</a>

Every pixel in Fashion-MNIST should be an integer in `[0, 255]`. To verify this, we drop into the **RDD API** and run a map-reduce: for each row we compute the minimum and maximum across all 784 pixel features, and then reduce across all rows to obtain the global min/max.


In [ ]:
# Convert DataFrame to RDD; each row is a pyspark.sql.Row.
# We slice out the 784 pixel columns (index 1 onwards - column 0 is the label).
rdd_train = df_fmnist_train.rdd

# Map: per-row (min_pixel, max_pixel) over the 784 pixel features
row_minmax = rdd_train.map(lambda row: (
    min(row[i] for i in range(1, 785)),
    max(row[i] for i in range(1, 785)),
))

# Reduce: global (min, max) across all rows
global_min, global_max = row_minmax.reduce(
    lambda a, b: (min(a[0], b[0]), max(a[1], b[1]))
)

print(f"Global pixel min (train): {global_min}")
print(f"Global pixel max (train): {global_max}")

# Sanity-check label range using the same RDD pattern
label_min, label_max = (
    df_fmnist_train.rdd
    .map(lambda row: (row["label"], row["label"]))
    .reduce(lambda a, b: (min(a[0], b[0]), max(a[1], b[1])))
)
print(f"Label min/max (train)  : {label_min} / {label_max}")


Global pixel min (train): 0
Global pixel max (train): 255


Label min/max (train)  : 0 / 9


<a class="anchor" id="9.4">

## **9.4 Type Consistency Check - SparkSQL**

[Back to TOP](#TOP)
</a>

We register the train set as a temporary view and use **Spark SQL** to spot records that fall outside the expected ranges. Because the dataset is 785 columns wide, we generate the WHERE clause programmatically.

For the type check itself, we iterate over **every** column in the schema, appending each column's type to a tuple of distinct types. Inspecting the tuple's size tells us whether the dataset is type-homogeneous (size 1 means all columns share a single type), and printing its contents reveals exactly which type(s) are present.


In [ ]:
# Register temp views for SQL queries
df_fmnist_train.createOrReplaceTempView("fmnist_train")
df_fmnist_test.createOrReplaceTempView("fmnist_test")

pixel_cols = [c for c in df_fmnist_train.columns if c.startswith("pixel")]

# Build a single OR-chained predicate that matches any out-of-range pixel
out_of_range_clause = " OR ".join(
    [f"{c} < 0 OR {c} > 255" for c in pixel_cols]
)

# Rows where at least one pixel is outside [0, 255]
bad_pixel_rows = spark.sql(f"""
    SELECT COUNT(*) AS n_bad_pixel_rows
    FROM   fmnist_train
    WHERE  {out_of_range_clause}
""").collect()[0]["n_bad_pixel_rows"]
print(f"Train rows with any pixel outside [0, 255]: {bad_pixel_rows}")

# Rows with invalid label (anything outside 0..9)
bad_label_rows = spark.sql("""
    SELECT COUNT(*) AS n_bad_labels
    FROM   fmnist_train
    WHERE  label < 0 OR label > 9
""").collect()[0]["n_bad_labels"]
print(f"Train rows with label outside [0, 9]      : {bad_label_rows}")

# ----- Full-schema type check via a distinct-types tuple ----------------
# Iterate over every one of the 785 columns; add the column type to the
# tuple only if it hasn't been seen yet. After the loop, the tuple's size
# tells us how many distinct types live in the schema; its contents reveal
# which types they are.
distinct_types = ()
for field in df_fmnist_train.schema.fields:
    t = field.dataType.simpleString()
    if t not in distinct_types:
        distinct_types = distinct_types + (t,)

print(f"Number of distinct column types across all {len(df_fmnist_train.columns)} columns: {len(distinct_types)}")
print(f"Distinct types found: {distinct_types}")
if len(distinct_types) == 1 and distinct_types[0] in ("int", "bigint", "smallint", "tinyint"):
    print("All columns are of a single integer type as expected.")
else:
    print("WARNING: schema is not uniformly integer-typed - investigate.")


Train rows with any pixel outside [0, 255]: 0
Train rows with label outside [0, 9]      : 0
Columns NOT of integer type: none


<a class="anchor" id="9.5">

## **9.5 Class Balance - SparkSQL**

[Back to TOP](#TOP)
</a>

Fashion-MNIST is documented as a perfectly balanced dataset (6,000 train + 1,000 test images per class). We verify this with a simple SQL `GROUP BY`.


In [ ]:
spark.sql("""
    SELECT label, COUNT(*) AS n
    FROM   fmnist_train
    GROUP BY label
    ORDER BY label
""").show()

spark.sql("""
    SELECT label, COUNT(*) AS n
    FROM   fmnist_test
    GROUP BY label
    ORDER BY label
""").show()


+-----+----+
|label|   n|
+-----+----+
|    0|6000|
|    1|6000|
|    2|6000|
|    3|6000|
|    4|6000|
|    5|6000|
|    6|6000|
|    7|6000|
|    8|6000|
|    9|6000|
+-----+----+

+-----+----+
|label|   n|
+-----+----+
|    0|1000|
|    1|1000|
|    2|1000|
|    3|1000|
|    4|1000|
|    5|1000|
|    6|1000|
|    7|1000|
|    8|1000|
|    9|1000|
+-----+----+



<a class="anchor" id="9.6">

## **9.6 Duplicates and Image-Format Consistency**

[Back to TOP](#TOP)
</a>

Two final integrity checks:

1. **Exact duplicates** - we count any rows that are bit-for-bit identical across the label column and all 784 pixels. Exact duplicates would inflate training-set statistics and bias evaluation.
2. **Image-format consistency** - every Fashion-MNIST image is documented to be 28x28, which means every row in the CSV must carry exactly 784 non-null pixel values. We verify this with the **same distinct-tuple pattern** used for the type check in 9.4: we iterate over rows via the RDD API, compute the count of non-null pixel values per row, and accumulate every new value seen into a tuple of distinct counts. A tuple of size 1 whose only element is `784` proves all images share the same format.


In [ ]:
# ----- 1. Exact duplicate detection (DataFrame API) ----------------------
n_train       = df_fmnist_train.count()
n_train_dedup = df_fmnist_train.dropDuplicates().count()
n_test        = df_fmnist_test.count()
n_test_dedup  = df_fmnist_test.dropDuplicates().count()

print(f"Train: total={n_train:,}, unique={n_train_dedup:,}, duplicates={n_train - n_train_dedup}")
print(f"Test : total={n_test:,}, unique={n_test_dedup:,}, duplicates={n_test - n_test_dedup}")

# ----- 2. Image-format consistency via distinct-tuple pattern -----------
# For each row, count non-null pixel values. All images should have 784.
# Iterate over the distinct values returned by Spark, appending each one
# to a tuple only if it has not been seen before - same pattern as the
# type check in 9.4.
pixel_col_idx = range(1, 785)  # column 0 is label, columns 1..784 are pixels

train_distinct_counts = (
    df_fmnist_train.rdd
    .map(lambda row: sum(1 for i in pixel_col_idx if row[i] is not None))
    .distinct()
    .collect()
)

distinct_formats = ()
for v in train_distinct_counts:
    if v not in distinct_formats:
        distinct_formats = distinct_formats + (v,)

print(f"Train - number of distinct image formats (non-null pixel counts): {len(distinct_formats)}")
print(f"Train - distinct counts found: {distinct_formats}")
if distinct_formats == (784,):
    print("All train images share the same 784-pixel format.")
else:
    print("WARNING: image formats are not uniform across the train set.")

# Repeat for the test set
test_distinct_counts = (
    df_fmnist_test.rdd
    .map(lambda row: sum(1 for i in pixel_col_idx if row[i] is not None))
    .distinct()
    .collect()
)

distinct_formats_test = ()
for v in test_distinct_counts:
    if v not in distinct_formats_test:
        distinct_formats_test = distinct_formats_test + (v,)

print(f"Test  - number of distinct image formats: {len(distinct_formats_test)}")
print(f"Test  - distinct counts found: {distinct_formats_test}")


Train: total=60,000, unique=59,957, duplicates=43
Test : total=10,000, unique=9,999, duplicates=1


Train - number of distinct image formats (non-null pixel counts): 1
Train - distinct counts found: (784,)
All train images share the same 784-pixel format.
Test  - number of distinct image formats: 1
Test  - distinct counts found: (784,)


The EDA confirms that Fashion-MNIST is clean as expected: no null values, all pixels in `[0, 255]`, all labels in `[0, 9]`, every column is already an integer type, and the class distribution is perfectly balanced across both splits. 

The preprocessing stage below is therefore minimal. We only need to enforce explicit `IntegerType` casts (defensive against `inferSchema` edge cases) and remove duplicates.


<a class="anchor" id="10">

# **10. Initial Preprocessing - Fashion-MNIST Dataset**

[Back to TOP](#TOP)
</a>

Given the EDA results, preprocessing is intentionally minimal: enforce integer types on every column as a defenseguard, drop any row that contains a null (none expected), and remove exact duplicate rows.

In [ ]:
from pyspark.sql.types import IntegerType

pixel_cols = [c for c in df_fmnist_train.columns if c.startswith("pixel")]


def _clean_fmnist(df, name):
    n_initial = df.count()

    # 1. Cast every column to IntegerType (defensive)
    for c in df.columns:
        df = df.withColumn(c, F.col(c).cast(IntegerType()))

    # 2. Drop nulls
    n_before_dropna = df.count()
    df = df.dropna()
    n_after_dropna = df.count()
    removed_nulls = n_before_dropna - n_after_dropna
    print(f"[{name}] Removed {removed_nulls} row(s) containing null values.")

    # 3. Drop exact duplicate rows
    n_before_dedup = df.count()
    df = df.dropDuplicates()
    n_after_dedup = df.count()
    removed_dups = n_before_dedup - n_after_dedup
    print(f"[{name}] Removed {removed_dups} exact duplicate row(s).")

    print(f"[{name}] Rows before cleaning: {n_initial:,} -> after cleaning: {n_after_dedup:,}")
    print()
    return df


df_fmnist_train_clean = _clean_fmnist(df_fmnist_train, "train")
df_fmnist_test_clean  = _clean_fmnist(df_fmnist_test,  "test")


[train] Removed 0 row(s) containing null values.


[train] Removed 43 exact duplicate row(s).
[train] Rows before cleaning: 60,000 -> after cleaning: 59,957

[test] Removed 0 row(s) containing null values.


[test] Removed 1 exact duplicate row(s).
[test] Rows before cleaning: 10,000 -> after cleaning: 9,999



In [ ]:
# Free the cached memory
df_fmnist_train.unpersist()
df_fmnist_test.unpersist()

<a class="anchor" id="11">

# **11. Save Preprocessed Datasets**

[Back to TOP](#TOP)
</a>



We are going to save both datasets to parquet format, even though the PaySim dataset was originally in csv, as it is the most suitable format for the task at hand.

In [ ]:
# Save taxi data back to Parquet (already Parquet, just saving cleaned version)
df_taxi_clean.write.mode("overwrite").parquet("data/clean/taxi_clean.parquet")

# Convert PaySim from CSV to Parquet
df_paysim_clean.write.mode("overwrite").parquet("data/clean/paysim_clean.parquet")

# Save Fashion-MNIST train/test splits to Parquet
df_fmnist_train_clean.write.mode("overwrite").parquet("data/clean/fashion_mnist_train_clean.parquet")
df_fmnist_test_clean.write.mode("overwrite").parquet("data/clean/fashion_mnist_test_clean.parquet")


26/05/14 18:42:21 WARN DAGScheduler: Broadcasting large task binary with size 1277.2 KiB
26/05/14 18:42:58 WARN DAGScheduler: Broadcasting large task binary with size 1277.3 KiB
